version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "themisguard-api"
s3_bucket = ""  # SAM will create this automatically
s3_prefix = "themisguard-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
    "Environment=dev",
    "JWTSecretKey=your-secret-key-change-in-production",
    "GCPProjectId="
]

[dev]
[dev.build]
[dev.build.parameters]
cached = true
parallel = true

[dev.deploy]
[dev.deploy.parameters]
stack_name = "themisguard-api-dev-debug"
s3_bucket = ""
s3_prefix = "themisguard-api-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev",
    "ProjectName=themisguard",
    "JWTSecretKey=your-secret-key-change-in-production-local-deploy",
    "StripeSecretKey=sk_test_placeholder",
    "StripePublishableKey=pk_test_placeholder",
    "StripeWebhookSecret=whsec_placeholder"
]

[staging]
[staging.build]
[staging.build.parameters]
cached = true
parallel = true

[staging.deploy]
[staging.deploy.parameters]
stack_name = "themisguard-api-staging"
s3_bucket = ""
s3_prefix = "themisguard-api-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=staging",
    "ProjectName=themisguard",
    "JWTSecretKey=your-secret-key-change-in-production",
    "StripeSecretKey=sk_test_...",
    "StripePublishableKey=pk_test_...",
    "StripeWebhookSecret=whsec_..."
]

[prod]
[prod.build]
[prod.build.parameters]
cached = true
parallel = true

[prod.deploy]
[prod.deploy.parameters]
stack_name = "themisguard-api-prod"
s3_bucket = ""
s3_prefix = "themisguard-api-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=prod",
    "ProjectName=themisguard",
    "JWTSecretKey=your-secret-key-change-in-production",
    "GCPProjectId=",
    "GoogleClientId=",
    "StripeSecretKey=sk_live_...",
    "StripePublishableKey=pk_live_...",
    "StripeWebhookSecret=whsec_...",
    "CustomDomainName=api.themisguard.com",
    "SSLCertificateArn=arn:aws:acm:us-east-1:YOUR_ACCOUNT:certificate/YOUR_CERT_ID"
]